# Bu iş akışı aşağıdaki iş akışlarından büyük ölçüde esinlenilmiştir:
# https://github.com/arichornlover/uYouEnhanced/blob/main/.github/workflows/buildapp.yml
# https://github.com/ISnackable/YTCubePlus/blob/main/.github/workflows/Build.yml
# https://github.com/BandarHL/BHTwitter/actions/workflows/build.yml

name: SCInsta'yı Derle ve Paketle 📦🚀✨🛠️

on:
  workflow_dispatch: # Bu iş akışını GitHub arayüzünden manuel olarak tetiklemeye izin verir. 🌐👆⚙️
    inputs:
      decrypted_instagram_url: # Şifresi çözülmüş Instagram IPA'sının doğrudan URL'si. 🔗🔐📱📥
        description: "Şifresi çözülmüş Instagram IPA'sının doğrudan URL'si"
        default: ""
        required: true
        type: string
      app_name: # Uygulama adı girişi (opsiyonel). 📝📱✨
        description: "Uygulama Adı (Opsiyonel - Boş bırakılırsa varsayılan kullanılır)"
        default: ""
        required: false
        type: string
      developer_name: # Geliştirici adı girişi (opsiyonel). 🧑‍💻✍️🌟
        description: "Geliştirici Adı (Opsiyonel - Boş bırakılırsa varsayılan kullanılır)"
        default: ""
        required: false
        type: string
      scinsta_version: # SCInsta tweak sürüm numarası girişi (opsiyonel). 🔢✨🔄
        description: "SCInsta Tweak Sürümü (Opsiyonel - Boş bırakılırsa control dosyasından alınır)"
        default: ""
        required: false
        type: string
      instagram_app_version: # Instagram uygulama sürüm numarası girişi (opsiyonel). 📱🔢✨
        description: "Instagram Uygulama Sürümü (Opsiyonel - Boş bırakılırsa orijinal IPA'nın sürümü kullanılır)"
        default: ""
        required: false
        type: string
      remove_app_icon: # Uygulama fotoğrafını kaldırma seçeneği (opsiyonel). 🖼️❌🚫
        description: "Uygulama Fotoğrafını Kaldır (Opsiyonel - Seçilirse boş ikonla derlenir)"
        default: false
        required: false
        type: boolean
      upload_artifact: # Oluşturulan paketi GitHub Artifacts'a yükleyip yüklemeyeceği. 📤📂✅☁️
        description: "Derleme sonucunu (artifact) yükle"
        default: true
        required: false
        type: boolean
          
concurrency: # Aynı anda birden fazla çalıştırmanın nasıl yönetileceğini belirler. 🚦🔄⏳🚫
  group: ${{ github.workflow }}-${{ github.ref }} # Aynı iş akışı ve referans için yalnızca bir çalıştırmaya izin verir.
  cancel-in-progress: true # Devam eden çalıştırmaları iptal eder.

jobs:
  build: # Derleme işi. 🏗️💻🍏📦
    name: SCInsta'yı Derle 🚀✨✅🛠️
    runs-on: macos-latest # İşin en son macOS sürümünde çalışacağını belirtir. 🍎💻
    permissions: # İşin sahip olduğu izinler. 🔑🔒
      contents: write # Depo içeriğine yazma izni verir. ✍️

    steps: # İşin adımları. 👣➡️
      - name: Ana Depoyu Çek 📥📂🔗🔄
        uses: actions/checkout@v4 # Depoyu çekmek için checkout eylemini kullanır.
        with:
          path: main # Depoyu 'main' dizinine çeker.
          submodules: recursive # Alt modülleri de özyinelemeli olarak çeker.

      - name: Bağımlılıkları Yükle 📦🔧⚙️📚
        run: brew install ldid dpkg make # Gerekli araçları (ldid, dpkg, make) Homebrew ile yükler.

      - name: PATH Ortam Değişkenini Ayarla 🛣️🌍⚙️➡️
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH # 'make' komutunun doğru sürümünü PATH'e ekler.

      - name: Theos'u Kur 🍏🛠️⚙️🚀
        uses: actions/checkout@v4 # Theos deposunu çekmek için checkout eylemini kullanır.
        with:
          repository: theos/theos # Theos'un GitHub deposu.
          ref: master # Master branch'ini çeker.
          path: ${{ github.workspace }}/theos # Theos'u çalışma alanındaki 'theos' dizinine çeker.
          submodules: recursive # Theos'un alt modüllerini de özyinelemeli olarak çeker.
            
      - name: SDK Önbellekleme 💾⚡️📥🔄
        id: SDK # Bu adım için bir ID belirler.
        uses: actions/cache@v4 # Önbellekleme eylemini kullanır.
        env:
          cache-name: iPhoneOS14.5.sdk # Önbellek adı.
        with:
          path: ${{ github.workspace }}/theos/sdks/ # Önbelleğe alınacak dizin.
          key: ${{ env.cache-name }} # Önbellek anahtarı.
          restore-keys: ${{ env.cache-name }} # Geri yüklenecek anahtarlar.

      - name: iOS SDK İndir ⬇️📱🌐📦
        if: steps.SDK.outputs.cache-hit != 'true' # Eğer SDK önbellekte yoksa çalışır.
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/xybp888/iOS-SDKs/ # iOS SDK'larını içeren depoyu klonlar.
          cd iOS-SDKs # Dizin değiştirir.
          git sparse-checkout set --no-cone iPhoneOS14.5.sdk # Sadece belirtilen SDK'yı çeker.
          git checkout # Çekilen SDK'yı etkinleştirir.
          mv *.sdk $THEOS/sdks # SDK'yı Theos'un SDK dizinine taşır.
        env:
          THEOS: ${{ github.workspace }}/theos # THEOS ortam değişkenini ayarlar.

      - name: Instagram IPA'yı Hazırla 📱📦🔗📥
        run: |
          cd main # Ana depo dizinine gider.
          mkdir -p packages # 'packages' dizini oluşturur.
          wget "$Instagram_URL" --no-verbose -O packages/com.burbn.instagram.ipa # Belirtilen URL'den Instagram IPA'sını indirir.
          ls -la packages # 'packages' dizininin içeriğini listeler.
            
        env:
          THEOS: ${{ github.workspace }}/theos # THEOS ortam değişkenini ayarlar.
          Instagram_URL: ${{ inputs.decrypted_instagram_url }} # Girişlerden alınan Instagram URL'sini kullanır.

      - name: SCInsta ve Instagram Sürümünü Belirle 🏷️🔢✨📄
        id: versions
        run: |
          # SCInsta Tweak Sürümünü Belirle
          SCINSTA_TWEAK_VERSION=""
          if [[ -n "${{ inputs.scinsta_version }}" ]]; then
            SCINSTA_TWEAK_VERSION="${{ inputs.scinsta_version }}"
            echo "SCInsta tweak sürümü manuel olarak ayarlandı: ${SCINSTA_TWEAK_VERSION}"
          else
            SCINSTA_TWEAK_VERSION=$(awk '/Version:/ {print $2}' main/control)
            echo "SCInsta tweak sürümü control dosyasından alındı: ${SCINSTA_TWEAK_VERSION}"
          fi
          echo "SCINSTA_TWEAK_VERSION=${SCINSTA_TWEAK_VERSION}" >> "$GITHUB_ENV"
          echo "scinsta_version=${SCINSTA_TWEAK_VERSION}" >> "$GITHUB_OUTPUT"

          # Instagram Uygulama Sürümünü Belirle (bu kısım build.sh'ye argüman olarak iletilmeli)
          INSTAGRAM_APP_VERSION=""
          if [[ -n "${{ inputs.instagram_app_version }}" ]]; then
            INSTAGRAM_APP_VERSION="${{ inputs.instagram_app_version }}"
            echo "Instagram uygulama sürümü manuel olarak ayarlandı: ${INSTAGRAM_APP_VERSION}"
          else
