name: Tüm İş Akışı Geçmişini Sil 🚨🗑️

on:
  workflow_dispatch: # Bu iş akışını sadece manuel olarak tetiklemeye izin verir

jobs:
  delete_all:
    runs-on: ubuntu-latest # GitHub CLI Ubuntu runner'da yüklü gelir
    permissions:
      contents: none
      actions: write # İş akışı çalıştırmalarını silebilmek için bu izne ihtiyaç duyarız

    steps:
      - name: GitHub CLI Yüklü mü Kontrol Et ve Doğrula
        run: |
          gh --version
          echo "GITHUB_TOKEN'ı gh CLI için yapılandırılıyor..."
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh auth status

      - name: Tüm Eski İş Akışı Çalıştırmalarını Direkt Sil 🔥
        run: |
          echo "Depodaki tüm iş akışı çalıştırmaları listeleniyor ve siliniyor..."
          # Tüm iş akışı ID'lerini al ve her birini sil
          # Not: Bu komut, başarılı olsa bile "yinelemeli olarak sil" gibi bir uyarı verebilir.
          # '--repo "${{ github.repository }}"' mevcut depoyu belirtir
          # '--limit 1000' bir seferde en fazla 1000 çalıştırmayı listeler, ihtiyaca göre artırılabilir
          # '--json databaseId' her çalıştırmanın ID'sini JSON formatında alır
          # 'jq -r '.[].databaseId'' bu JSON'dan sadece ID'leri çıkarır
          # 'xargs -I {} gh run delete {} --repo "${{ github.repository }}"' her ID için silme komutunu çalıştırır.
          
          gh run list --repo "${{ github.repository }}" --limit 1000 --json databaseId | jq -r '.[].databaseId' | xargs -I {} gh run delete {} --repo "${{ github.repository }}" --yes

          echo "Silme işlemi tamamlandı. Değişikliklerin GitHub arayüzünde yansıması biraz zaman alabilir."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # gh CLI'ın token'ı kullanmasını sağlar
