name: Tüm İş Akışı Geçmişini Sil 🚨🗑️

on:
  workflow_dispatch: # Bu iş akışını sadece manuel olarak tetiklemeye izin verir

jobs:
  delete_all:
    runs-on: ubuntu-latest
    permissions:
      contents: none
      actions: write # İş akışı çalıştırmalarını silebilmek için bu izne ihtiyaç duyarız

    steps:
      - name: zTüm Eski İş Akışı Çalıştırmalarını Direkt Sil 🔥
        uses: actions/delete-workflow-runs@v5
        with:
          # Tüm çalıştırmaları silmek için 'days' parametresini çok düşük bir sayıya ayarlıyoruz.
          # Ancak aksiyonun doğası gereği, en az bir çalıştırma kalabilir veya yeni
          # tetiklenen çalıştırma anında silinemeyebilir.
          days: 1 # 1 günden eski olanları sil (bu pratik olarak tüm geçmişi kapsar)
          # Hangi iş akışlarını sileceğimizi belirtmezsek, tüm iş akışlarının çalıştırmalarını siler.
          # Kendisini (bu iş akışını) de silmeye çalışacaktır, ancak çoğu durumda tamamlanmadan silinemez.
          token: ${{ secrets.GITHUB_TOKEN }}
