name: Tüm İş Akışı Geçmişini Sil 🚨🗑️

on:
  workflow_dispatch: # Bu iş akışını sadece manuel olarak tetiklemeye izin verir

jobs:
  delete_all:
    runs-on: ubuntu-latest
    permissions:
      contents: none
      actions: write # İş akışı çalıştırmalarını silebilmek için bu izne ihtiyaç duyarız

    steps:
      - name: Tüm Eski İş Akışı Çalıştırmalarını Direkt Sil 🔥
        # BURAYI DEĞİŞTİRİYORUZ!
        uses: mikecparr/delete-workflow-runs@v2
        with:
          # mikecparr/delete-workflow-runs@v2 için 'older-than' parametresi kullanılabilir
          # Bu, belirli bir süreden daha eski olan tüm çalıştırmaları hedefler.
          # '0' gün belirterek pratik olarak tüm geçmişi hedefleriz.
          older-than: '0 days'
          # Ayrıca, silmek istediğiniz belirli iş akışlarının adlarını da listeleyebilirsiniz.
          # Tüm iş akışlarını silmek için bu parametreyi boş bırakın veya kullanmayın.
          # workflow: 'Build and Package SCInsta, My Other Workflow' # Örnek: Belirli iş akışları için
          # min-runs-to-keep: 0 # Her iş akışı için minimum çalıştırma sayısı, 0 tümünü siler
          # dry-run: true # Gerçekten silmeden önce ne olacağını görmek için 'true' yapın (önerilir!)
          token: ${{ secrets.GITHUB_TOKEN }}
