name: Tüm İş Akışı Geçmişini Sil 🚨🗑️

on:
  workflow_dispatch: # Bu iş akışını sadece manuel olarak tetiklemeye izin verir

jobs:
  delete_all:
    runs-on: ubuntu-latest # GitHub CLI Ubuntu runner'da yüklü gelir
    permissions:
      contents: none
      actions: write # İş akışı çalıştırmalarını silebilmek için bu izne ihtiyaç duyarız

    steps:
      - name: GitHub CLI Yüklü mü Kontrol Et ve Doğrula
        run: |
          gh --version
          echo "GITHUB_TOKEN'ı gh CLI için yapılandırılıyor..."
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh auth status

      - name: Tüm Eski İş Akışı Çalıştırmalarını Direkt Sil 🔥
        run: |
          echo "Depodaki tüm iş akışı çalıştırmaları listeleniyor ve siliniyor..."
          # Tüm iş akışı ID'lerini al
          RUN_IDS=$(gh run list --repo "${{ github.repository }}" --limit 1000 --json databaseId | jq -r '.[].databaseId')

          # Her bir çalıştırma ID'si için silme komutunu çalıştır
          # yes | gh run delete komutu, her onay sorgusuna 'y' yanıtı verir.
          echo "$RUN_IDS" | xargs -I {} bash -c 'echo "Siliniyor: {}"; yes | gh run delete {} --repo "${{ github.repository }}"'

          echo "Silme işlemi tamamlandı. Değişikliklerin GitHub arayüzünde yansıması biraz zaman alabilir."
        env:
          GH_TOKEN: ${{ secrets.TOKEN }} # gh CLI'ın token'ı kullanmasını sağlar
